endgame/urls.py
#****************************************************************************
#   Unidad: urls.py
#   Descripción: Servicio de routing de la aplicación. 
#   
#   Autor: Jojann De Vargas
#   Fecha: 20-02-2020
# 
#   Historial de modificaciones
#   Fecha           usuario         descripción
#   20-02-2020      jdevargas       Creación.
# 
# *************************************************************************** 
from django.urls          import path
from django.views.generic import TemplateView
from .                    import views


app_name = 'endgame'
urlpatterns = [

    # Servicios principales
    # 1. Vista principal.
    path('', views.index, name='index'),
    
    # 2. Vista inicial del juego (donde se permite selecionar la opción o respuesta).
    path('<int:player_id>/game/', views.game, name='game'),
    
    # 3. Servicio que valida si ya se conectó otro jugador a la partida.
    path('<int:player_id>/<int:player_number>/wait/', views.wait, name='wait'),
    
    # 4. Servicio que guarda la respues de un jugador.
    path('<int:game_id>/<int:player_number>/<int:option_id>/answergame/', views.answergame, name='answergame'),
   
    # 5. Servicio que permite validar si el otro jugador ya respondió.
    path('<int:game_id>/<int:player_number>/gamestatus/', views.gamestatus, name='gamestatus'),
    
    # 6. Servicio para visualizar la pantalla de resultados de la partida.
    path('gameresults/', views.gameresults, name='gameresults'),

    # Servicios utilitarios
    # Servicio utilitario para obtener el código Javascript que permite ejecutar el servicio 3.
    path('<int:player_id>/game/work_game.js', (TemplateView.as_view(template_name="endgame/work_game.js", content_type='application/javascript', )), name='work_game.js'),
    
    # Servicio utilitario para obtener el código Javascript que permite ejecutar el servicio 5.
    path('<int:player_id>/game/work_gamestatus.js', (TemplateView.as_view(template_name="endgame/work_gamestatus.js", content_type='application/javascript', )), name='work_gamestatus.js'),
]

endgame/templates/endgame/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
</head>
<body>

    {% if error %}
        <p><strong>{{ error }}</strong></p>        
    {% endif %}

    <a href="{% url 'endgame:index' %}">Start</a> 

</body>
</html>

endgame/templates/endgame/game.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Endgame - play</title>
    <link rel="stylesheet" type="text/css" href="{% static 'endgame/style.css' %}">
    <script src="{% static 'endgame/game.js' %}"></script>
    
</head>
<body>
    <h1> Welcome a new GAME! Are you ready? </h1>

    <button onclick="startWorker()">Ready</button>
    
    <h2 id="state" name="state"></h2>

    <form action="{% url 'endgame:gameresults' %}" method="post">
        
        <input type="text" value="{{ game_id }}" name="game_id" id="game_id" readonly hidden>
        <input type="text" value="{{ player_id }}" name="player_id" id="player_id" readonly hidden>
        <input type="text" value="{{ player_number }}" name="player_number" id="player_number" readonly hidden>
        
        {% csrf_token %}
        {% for option in options.all %}
            <input type="radio" onClick="updateAnswer()" name="option_id" id="option{{ forloop.counter }}" value="{{ option.id }}" >
            <label for="option{{ forloop.counter }}">{{ option.description }}</label><br>
        {% endfor %}
        
        <input type="submit" value="Answer" id="answer" name="answer" disabled>
        <p id="msj_wait" name="msj_wait"></p>
    </form>

</body>
</html>

endgame/templates/endgame/gameresults.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Endgame - Results</title>
</head>
<body>
    
    <h1>You are:
        {% if player_number == '1' %}
            {{ player_name1 }}
        {% else %}
            {{ player_name2 }}
        {% endif %}
    </h1>
    <h1>Answer by player: {{ player_name1 }}</h1>
        {% for option in options.all %}
            
            {% if option.id == opt_player1 %}
                <input type="radio" name="option1_{{ forloop.counter }}" id="option1_{{ forloop.counter }}" value="{{ option.id }}" checked disabled>
                <label for="option{{ forloop.counter }}">{{ option.description }}</label><br>
            {% else %}
                <input type="radio" name="option1_{{ forloop.counter }}" id="option1_{{ forloop.counter }}" value="{{ option.id }}" disabled>
                <label for="option{{ forloop.counter }}">{{ option.description }}</label><br>
            {% endif %}

        {% endfor %}

        <h1>Answer by player: {{ player_name2 }}</h1>
        {% for option in options.all %}
            {% if option.id == opt_player2 %}
                <input type="radio" name="option2_{{ forloop.counter }}" id="option2_{{ forloop.counter }}" value="{{ option.id }}" checked disabled>
                <label for="option{{ forloop.counter }}">{{ option.description }}</label><br>
            {% else %}
                <input type="radio" name="option2_{{ forloop.counter }}" id="option2_{{ forloop.counter }}" value="{{ option.id }}" disabled>
                <label for="option{{ forloop.counter }}">{{ option.description }}</label><br>
            {% endif %}
        {% endfor %}

        <h1>Results: {{ results_msj }}</h1>
</body>
</html>

endgame/templates/endgame/index.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Endgame - register</title>
</head>
<body>

    <h1>Welcome! for you can play please enter your name</h1>

{% block content %}
    <h2>Now create a new fun game</h2>
    <form method="POST" class="post-form" >{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">To play</button>
    </form>
    {% if error %}
        <p><strong>{{ error }}</strong></p>        
    {% endif %}
    {% if player_id %}
        <a href="{% url 'endgame:game' player_id %}">I am [{{ player_name }}]</a> 
    {% endif %}
    
{% endblock %}

</body>
</html>